name: CI/CD Pipeline
# nome da pipelne, de sua preferencia, geralmente qual função ela ira executar.

# quando a pipeline vai ser executada, gatilhos no caso apartir de qual elemento escolhido ela iniciar seu trabalho/
on:  # palavra chave.
  push:  # gatilhos escolhido
    branches:
      - main
#

# inicio dos trabalhos que ela executará apartir do evento que foi definido.
jobs: 
  build:  #tarefa que foi defininda por voce.
    runs-on: ubuntu-latest  #maquina a ser usada dentro do git hub para fazer esse acão "serviço"
# um etapa de trabalho definida

    steps:  # apartir do momento que seguir os passos entra os steps " tarefas a serem feitas "
    - name: Checkout code  # geralmente a cada tarefa agente colocado um nome para atribuido apartir da tarefa atribuido que voce definir 
      uses: actions/checkout@v2  # por baixo dos panos esse é um arquivo pre definido pelo o git hub que vai 
      #clonar seu repositorio pra dentro do ambiente de execução
#
    - name: Build Docker image
      run: docker build -t nodejs-ci-cd .
# envia a imagem para o docker hub , configurar os secrets no github primeiro
#
    - name: Push Docker image to Docker Hub  # nome de exempro
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |



         "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag nodejs-ci-cd ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-ci-cd
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-ci-cd
# entra no docker hub e cria uma imagem com o nome nodejs-ci-cd
# docker push envia a imagem para o docker hub
