name: Deploy to netfily

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to netfily
      env:
        HEROKU_API_KEY: ${{ secrets.NETFILY_API_KEY }}
      run: |
        netlify container:login
        netlify container:push web -a myapp
        netlify container:release web -a myapp
